services:
  redis:
    image: redis:latest
    container_name: redis-service
    ports:
      - "6379:6379"
    networks:
      - microservices-network
    volumes:
      - redis-data:/data

  mongodb:
    image: mongo:latest
    container_name: mongodb-service
    ports:
      - "27017:27017"
    networks:
      - microservices-network
    volumes:
      - mongodb-data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nodejs-api
    ports:
      - "8080:8080"
    networks:
      - microservices-network
    depends_on:
      - redis
      - mongodb
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - MONGO_URI=mongodb://admin:password@mongodb:27017/microservices?authSource=admin
      - PORT=8080

networks:
  microservices-network:
    driver: bridge

volumes:
  redis-data:
  mongodb-data: