services:
  redis:
    image: redis:latest
    container_name: redis-service
    restart: unless-stopped
    volumes:
      - redis-data:/data

  mongodb:
    image: mongo:latest
    container_name: mongodb-service
    restart: unless-stopped
    volumes:
      - mongodb-data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD:-password}

  api:
    image: ${DOCKER_USERNAME}/microservices-api:${API_VERSION:-latest}
    container_name: nodejs-api
    restart: unless-stopped
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - MONGO_URI=mongodb://admin:${MONGO_PASSWORD:-password}@mongodb:27017/microservices?authSource=admin
      - PORT=8080
    depends_on:
      - redis
      - mongodb

volumes:
  redis-data:
  mongodb-data: 